### ISSUE TITLE
adapt to nuscene dataset

### ISSUE THREAD

**Issue by wutongtong** [OPEN-AIR-SUN/mars#115]
Hi, I'm trying to adapt Mars to nuscene dataset, I used the frontleft， front， frontright，three cameras to reconstruct the scene，but the result of the frontleft is a bit strange (like the following image).  Do you have any suggestion about this? Thank you in advance！
<img width="524" alt="截屏2023-12-11 21 21 34" src="https://github.com/OPEN-AIR-SUN/mars/assets/13852651/8cb52da4-4bbd-4415-bf5f-196ce6771df7">

**Comment by wuzirui** [comment]
Could you provide some more information?

**Comment by wutongtong** [comment]
can you open this link？[](https://api.wandb.ai/links/wutongtong1619/t166m1lm)，In this version，I used the v1.0-mini version dataset，I used frontleft and front two cameras，and the scene id is 0757，I used the first 15 frames to train Mars

**Comment by wuzirui** [comment]
just from the rendered object_rgb images, it can be seen that the object bounding boxes are too large so that some of the background is included in the bbox.

<img width="524" src="https://storage.googleapis.com/wandb-production.appspot.com/wutongtong1619/nerfstudio-project/95732775/media/images/Eval%20Images/objects_rgb_10000_0b16cbfc4f90448f76ef.png?Expires=1702307467&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Z5lPlZ7eYhACCqQ20%2F9aqTN3S%2FroCeF3VL0nzQtzoYV0ZiH95alCV%2Buy2%2FgRWIkTDCXwDy%2BGmkIk%2BDcR2c2UP1t4xgcyB3oafqmcEAKehoH%2F8iHflRQ2vq4Ioo32IfEascOL9nkI5CTpL8qhOClLRhynBQ9R7xvuZUG6GvPvuMpI3P7cd4S3IIRad7Pjv0HdMxa7Vx9j7EU7tfV2ae3mOXfyIQVSKaeU5Cy6vLxYtLbnXzN3MPMB%2Bj348xHGXR5MHdn5M%2FBvkJwf%2BXxIpChEOeg9T2Gd2Dl8YbaOa%2F5n70Xpjt%2B9KE1n%2FH%2BgljCbtKOilKaztyrGgv6LWxfeoNyXow%3D%3D">

**Comment by wutongtong** [comment]
I reduced the size of the bounding box，but the rendering results are still strange， here is the link [wandb](https://wandb.ai/wutongtong1619/nerfstudio-project/reports/Untitled-Report--Vmlldzo2MjM2Mjcy?accessToken=r65v6fnju49uzhe06k9akv8ai9k7jbvz7sonqmvljna7ilqzlk8mxetwpq9mqp8k)

**Comment by wuzirui** [comment]
Yes, this is actually what we also concluded for the nuscenes dataset. The provided boxes & poses are a bit too noisy.

**Comment by szhang963** [comment]
@wutongtong hi, I want to ask a question for you.  Did you reconstruct the nuscene data succesfully? And how to code the dataparser for 6v cameras?
