### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'background_model'

### ISSUE THREAD

**Issue by yanjh97** [OPEN-AIR-SUN/mars#132]
Hi, I tried to run
```
python nerfstudio/nerfstudio/scripts/train.py mars-kitti-car-depth-recon --data /data/kitti-MOT/training/image_02/0006
```
got an error:
```
Traceback (most recent call last):
    entrypoint()
    tyro.cli(
    output = _cli_impl(
    out, consumed_keywords = _calling.call_from_args(
    value, consumed_keywords_child = call_from_args(
    value, consumed_keywords_child = call_from_args(
    value, consumed_keywords_child = call_from_args(
    return unwrapped_f(*positional_args, **kwargs), consumed_keywords  # type: ignore
TypeError: __init__() got an unexpected keyword argument 'background_model'
```
Can you give some suggestions? Thanks.

**Comment by antithing** [comment]
I have the same issue, did you manage to solve this?

**Comment by xBeho1der** [comment]
Hi! @antithing and @yanjh97 

We have received your message, and we will fix it as soon as possible. Thanks!

**Comment by xBeho1der** [comment]
You can add a version constraint in the `pyproject` file to limit the nerfstudio version to 0.3.4. Then, you can check if this issue has been fixed.

**Comment by ScottDeng114514** [comment]
> You can add a version constraint in the `pyproject` file to limit the nerfstudio version to 0.3.4. Then, you can check if this issue has been fixed.

Thanks for your replay,but the problem still exists.
![2024-02-01 10-04-29 的屏幕截图](https://github.com/OPEN-AIR-SUN/mars/assets/96806352/9456ef9e-ad0c-4c24-9406-5cceb48378f2)

**Comment by amoghskanda** [comment]
hey, facing the same issue. Changed the version of nerfstudio as well as mentioned above, still doesn't seem to work. Did anybody fix it?

**Comment by xBeho1der** [comment]
Hi there! @amoghskanda @antithing @yanjh97 @ScottDeng114514 As Nerfstudio bumped its version to 1.0.0, there might be some version-related issues. Thank you all for your responses.

I think that this bug is caused by an incorrect `tyro` version. You can try using [this branch](https://github.com/OPEN-AIR-SUN/mars/tree/chenjt/issue_132) and if there are no issues, I will fix it as soon as possible and update it on PyPI. 

I suggest that you pull the code and perform a local installation by using the command `pip install -e .` in mars directory.

**Comment by ScottDeng114514** [comment]
It works, now I can train my model from scratch normally! Thanks a lot.

**Comment by yanjh97** [comment]
It works for me, too. Thanks for your help.

**Comment by amoghskanda** [comment]
hey, I was able to fix that but ran into another issue
