### ISSUE TITLE
How to adapt to roadside dataset?

### ISSUE THREAD

**Issue by xiaosu-zhu** [OPEN-AIR-SUN/mars#25]
Hi, thanks for your great work. I notice that you have shown a result that was running on the DAIR-V2X dataset but you have not release relevant data parser and training config. Do you have the plan to release them? If it is not convenient, could you give me some tips on how to make adaptations on this kind of dataset? For example, how to obtain the car latents on this dataset? How to handle the camera ex/intrinsics and convert them to the vkitti format? Meanwhile, there is no motion on camera poses and there is only mono camera, does it affect the depth estimation on roadside background? Thanks a lot in advance.

**Comment by wuzirui** [comment]
Hi, the dataparser for the DAIR-V2X dataset is not planned to be released. However, you can implement it based on the VKITTI dataparser very quickly since the roadside camera is fixed and what you only need to care about is the relative object poses.

> How to obtain the car latents on this dataset? 

Our CarNeRF model is from [CarStudio](https://github.com/lty2226262/Car_studio), and we are sorry that we cannot provide the training scripts for their project at this period. However, you can fix the CarNeRF model from KITTI/VKITTI dataset and use a randomized car latents initialization and perform test-time optimization.

> How to handle the camera ex/intrinsics and convert them to the vkitti format?

In general, we assert the y-axis of the world space is the vertical axes, and the camera axes following the NeRFStudio convention of [Right Up Backward].

> there is no motion on camera poses and there is only mono camera, does it affect the depth estimation on roadside background?

I don't see any problem on mono-depth estimation so far.

Hope this answer helps!

**Comment by xiaosu-zhu** [comment]
Hi @wuzirui , thanks very much for your practices, I would take a try.

**Comment by wutongtong** [comment]
> ataparser for the DAIR-V2X dataset is not planned to be released. H
Did you tried to convert DAIR-V2X dataset to Kitti dataset format，and then use the kitti dataparser directly？
